### ISSUE TITLE
与豆腐世界豆浆冲突

### ISSUE THREAD

**Issue by Bread-NiceCat** [Bread-NiceCat/CandyCraftCE#6]
![image](https://github.com/user-attachments/assets/c6b41e99-ecab-4400-bfb7-8316d8508ef2)

**Comment by Bread-NiceCat** [comment]
1.21未发现此问题
![385f2381395ac5a43c8abad1feafcd52](https://github.com/user-attachments/assets/168ec177-2903-4875-8acc-e0b4d4dd2e71)

**Comment by Bread-NiceCat** [comment]
1.20.1问题成功复现
```
[278月2024 01:35:30.461] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.material.Fluid.m_6212_(net.minecraft.world.level.material.Fluid)" because "this.f_40687_" is null
	at net.minecraft.world.item.BucketItem.handler$zzk000$checkExtraContent(BucketItem.java:540) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.world.item.BucketItem.m_142131_(BucketItem.java) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.world.item.BucketItem.m_7203_(BucketItem.java:90) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:275) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233716_(MultiPlayerGameMode.java:368) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233721_(MultiPlayerGameMode.java:356) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1720) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23174!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-Forge_47.3.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
[278月2024 01:35:31.070] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server

```

**Comment by Bread-NiceCat** [comment]
已定位到异常点
https://github.com/Bread-NiceCat/CandyCraftCE/blob/549a85160313ec81d22124722e2d30417a2ca147/common/src/main/java/cn/breadnicecat/candycraftce/mixin/MixinBucketItem.java#L40

**Comment by Bread-NiceCat** [comment]
![image](https://github.com/user-attachments/assets/fa7a2304-29d3-4c94-8d65-8aae214c1283)
